apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
  selector:
    app: java-pod
  
  
