apiVersion: v1
kind: Pod
metadata:
  name: java-pod
  labels:
    app: java-pod
spec:
  containers:
    - name: java-container
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: java-app-configmap